### ISSUE TITLE
Undocumented test1.tpl behaviour 

### ISSUE THREAD

**Issue by cefn** [pfalcon/utemplate#2]
Having successfully tested and run the example ```squares.tpl``` I tried a more advanced example ```test1.tpl``` like...

```$ micropython ./utemplate_util.py run examples/test1.tpl```

Although the compile stage seemed to properly complete (generating the code inlined below) attempting to run the compliled code through the utemplate_util.py test harness resulted in the following error.

```
$ micropython ./utemplate_util.py run examples/test1.tpl 
Traceback (most recent call last):
  File "./utemplate_util.py", line 38, in <module>
TypeError: render() takes 2 positional arguments but 0 were given
```

Of course it turned out that test1.tpl was expecting additional arguments (as implied by the positional arguments in the generated code) and passing these to the command line led to a correct run.

```$ micropython ./utemplate_util.py run examples/test1.tpl "varValue" "anotherValue"```

```
# Autogenerated file
def render(var, another):
    yield """hello
"""
    for i in range(5):
        if i % 2:
            yield """world
"""
        elif i % 3 == 0:
            yield """something else
"""
        else:
            yield """skies
"""
        yield """text"""
        yield str(i + 10)
        yield """
"""
    yield """trailer
"""
```

**Comment by pfalcon** [comment]
> Of course

Of course. But indeed, maybe this "obvious" thing should be pronounced explicitly, hence https://github.com/pfalcon/utemplate/commit/80648590efc9013a5f1f7981cc305345327dd7f1
